# Generated by Django 5.0 on 2023-12-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('education', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('certify', models.CharField(max_length=200)),
                ('taxSoftware', models.CharField(max_length=200)),
                ('availability', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('years', models.PositiveIntegerField()),
                ('clientInteraction', models.TextField()),
                ('legislationKnowledge', models.TextField()),
                ('teamwork', models.TextField()),
                ('problemSolving', models.TextField()),
                ('professionalDevelopment', models.TextField()),
            ],
        ),
    ]
