# Generated by Django 5.0 on 2023-12-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='availability',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='certify',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='clientInteraction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='education',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='legislationKnowledge',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='problemSolving',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='professionalDevelopment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='taxSoftware',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='teamwork',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
