# Generated by Django 5.0 on 2023-12-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_apply_address_alter_apply_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
