# Generated by Django 5.0 on 2023-12-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_apply_education_alter_apply_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
