# Generated by Django 5.0 on 2024-01-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_clientinteraction_apply_workexperience_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apply',
            new_name='Application',
        ),
    ]
