# Generated by Django 5.0 on 2024-03-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_application_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
