# Generated by Django 5.0 on 2024-03-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_application_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
