# Generated by Django 5.0 on 2024-03-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_application_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='file',
        ),
        migrations.AddField(
            model_name='application',
            name='middle',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
