# Generated by Django 5.0 on 2024-06-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_application_file_application_middle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='name',
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
