# Generated by Django 5.0 on 2024-06-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_application_name_application_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='job',
        ),
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
