# Generated by Django 5.0 on 2024-06-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_application_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='overallScore',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
