# Generated by Django 5.0 on 2024-06-24 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_application_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='reasonForApplying',
            new_name='WhyTheyWantToJoin',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reference1Name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reference1Phone',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reference1Relationship',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reference2Name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reference2Phone',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reference2Relationship',
        ),
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
    ]
