# Generated by Django 5.0 on 2024-06-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_application_recentreasonforleaving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='years',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
