# Generated by Django 5.0 on 2024-06-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_application_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='availability',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='certifications',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='overallScore',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='taxSoftware',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='years',
            field=models.TextField(blank=True, null=True),
        ),
    ]
